# Generated by Django 6.0.5 on 2026-05-30 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('episode', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='characters', to='MoviePlanetApi.film')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('climate', models.CharField(blank=True, max_length=255)),
                ('terrain', models.CharField(blank=True, max_length=255)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('residents', models.ManyToManyField(blank=True, related_name='planets', to='MoviePlanetApi.character')),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('crew', models.IntegerField(blank=True, null=True)),
                ('pilots', models.ManyToManyField(blank=True, related_name='starships', to='MoviePlanetApi.character')),
            ],
        ),
    ]
