# Generated by Django 6.0.5 on 2026-05-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_EXAMPLE', '0002_project_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
